=== oussama-denden/tos/opale-api/src/test/resources/dtd/Opale.dtd
<!ELEMENT dataset (keygen*,client*,draft*, draftLigne*, draftLigneDetail*, commande*, commandeLigne*, commandeLigneDetail*, tarif*, frais*,signature*,paiement*,reduction*)>

<!ELEMENT draft EMPTY>
<!ATTLIST draft
    id CDATA #IMPLIED
    reference CDATA #IMPLIED
    clientAFacturerId CDATA #IMPLIED
    clientALivrerId CDATA #IMPLIED
    clientSouscripteurId CDATA #IMPLIED
    codePartenaire CDATA #IMPLIED
    qui CDATA #IMPLIED
    ip CDATA #IMPLIED
    canal CDATA #IMPLIED
    timestamp CDATA #IMPLIED
    referenceExterne CDATA #IMPLIED
    dateAnnulation  CDATA #IMPLIED
>
<!ELEMENT draftLigne EMPTY>
<!ATTLIST draftLigne
    id CDATA #IMPLIED
    reference CDATA #IMPLIED
    referenceTarif CDATA #IMPLIED
    dateCreation CDATA #IMPLIED
    qui CDATA #IMPLIED
    ip CDATA #IMPLIED
    canal CDATA #IMPLIED
    timestamp CDATA #IMPLIED
    draftId CDATA #IMPLIED
    referenceOffre CDATA #IMPLIED
     geste CDATA #IMPLIED
>
<!ELEMENT draftLigneDetail EMPTY>
<!ATTLIST draftLigneDetail
     id CDATA #IMPLIED
    referenceSelection CDATA #IMPLIED
    referenceChoix CDATA #IMPLIED
    referenceTarif CDATA #IMPLIED
    configurationJson CDATA #IMPLIED
    dependDe CDATA #IMPLIED
    draftLigneId CDATA #IMPLIED
>

<!ELEMENT tracage EMPTY>
<!ATTLIST tracage
     id CDATA #IMPLIED
    referenceDraft CDATA #IMPLIED
    action CDATA #IMPLIED
    user CDATA #IMPLIED
    date CDATA #IMPLIED
>

<!ELEMENT keygen EMPTY>
<!ATTLIST keygen
     id CDATA #IMPLIED
    referenceDraft CDATA #IMPLIED
    entite CDATA #IMPLIED
    prefix CDATA #IMPLIED
>

<!ELEMENT client EMPTY>
<!ATTLIST client
     id CDATA #IMPLIED
    adresseId CDATA #IMPLIED
    clientId CDATA #IMPLIED
    canal CDATA #IMPLIED
  ip  CDATA #IMPLIED
  qui  CDATA #IMPLIED
  timestamp  CDATA #IMPLIED
  tva CDATA #IMPLIED
>

<!ELEMENT commande EMPTY>
<!ATTLIST commande
    id CDATA #IMPLIED
    reference CDATA #IMPLIED
    referenceDraft CDATA #IMPLIED
    clientAFacturerId CDATA #IMPLIED
    clientALivrerId CDATA #IMPLIED
    clientSouscripteurId CDATA #IMPLIED
    dateCreation CDATA #IMPLIED
    dateTransformationContrat CDATA #IMPLIED
    dateAnnulation CDATA #IMPLIED
    qui CDATA #IMPLIED
    ip CDATA #IMPLIED
    canal CDATA #IMPLIED
    timestamp CDATA #IMPLIED
    codePartenaire CDATA #IMPLIED
   
>

<!ELEMENT commandeLigne EMPTY>
<!ATTLIST commandeLigne
    id CDATA #IMPLIED
    dateCreation CDATA #IMPLIED
    qui CDATA #IMPLIED
    ip CDATA #IMPLIED
    canal CDATA #IMPLIED
    timestamp CDATA #IMPLIED
    gamme CDATA #IMPLIED
    label CDATA #IMPLIED
    modeFacturation CDATA #IMPLIED
    typeProduit CDATA #IMPLIED
    referenceOffre CDATA #IMPLIED
    referenceContrat CDATA #IMPLIED
    secteur CDATA #IMPLIED
    commandeId CDATA #IMPLIED
    tarifId CDATA #IMPLIED
    geste CDATA #IMPLIED
>

<!ELEMENT commandeLigneDetail EMPTY>
<!ATTLIST commandeLigneDetail
    id CDATA #IMPLIED
    configurationJson CDATA #IMPLIED
    referenceSelection CDATA #IMPLIED
    referenceChoix CDATA #IMPLIED
    label CDATA #IMPLIED
    typeProduit CDATA #IMPLIED
    dependDe CDATA #IMPLIED
    commandeLigneId CDATA #IMPLIED
    tarifId CDATA #IMPLIED
>

<!ELEMENT tarif EMPTY>
<!ATTLIST tarif
     id CDATA #IMPLIED
    duree CDATA #IMPLIED
    engagement CDATA #IMPLIED
    frequence CDATA #IMPLIED
    prix CDATA #IMPLIED
    reference CDATA #IMPLIED
    typeTVA CDATA #IMPLIED
>

<!ELEMENT frais EMPTY>
<!ATTLIST frais
     id CDATA #IMPLIED
    label CDATA #IMPLIED
    montant CDATA #IMPLIED
    politique CDATA #IMPLIED
    politiqueIndex CDATA #IMPLIED
    reference CDATA #IMPLIED
    typeFrais CDATA #IMPLIED
    tarifId CDATA #IMPLIED
>

<!ELEMENT signature EMPTY>
<!ATTLIST signature
    id CDATA #IMPLIED
    reference CDATA #IMPLIED
    mode CDATA #IMPLIED
    timestampSignature CDATA #IMPLIED
    footprint CDATA #IMPLIED
    idSignature  CDATA #IMPLIED
    qui CDATA #IMPLIED
    ip CDATA #IMPLIED
    canal CDATA #IMPLIED
    timestamp CDATA #IMPLIED
    referenceCommande CDATA #IMPLIED
    dateAnnulation  CDATA #IMPLIED
    timestampIntention CDATA #IMPLIED
    dateCreation CDATA #IMPLIED
>

<!ELEMENT paiement EMPTY>
<!ATTLIST paiement
    id CDATA #IMPLIED
    infoPaiement CDATA #IMPLIED
    modePaiement CDATA #IMPLIED
    montant CDATA #IMPLIED
    reference CDATA #IMPLIED
    referenceCommande CDATA #IMPLIED
    qui CDATA #IMPLIED
    ip CDATA #IMPLIED
    canal CDATA #IMPLIED
    timestamp CDATA #IMPLIED
    timestampIntention CDATA #IMPLIED
    timestampPaiement CDATA #IMPLIED
    typePaiement CDATA #IMPLIED
    dateCreation CDATA #IMPLIED
>

<!ELEMENT reduction EMPTY>
<!ATTLIST reduction
    id CDATA #IMPLIED
    dateDebut CDATA #IMPLIED
    dateFin CDATA #IMPLIED
    label CDATA #IMPLIED
    nbUtilisationMax CDATA #IMPLIED
    reference CDATA #IMPLIED
    referenceDraft CDATA #IMPLIED
    referenceFrais CDATA #IMPLIED
    referenceLigne CDATA #IMPLIED
    referenceLigneDetail CDATA #IMPLIED
    referenceTarif CDATA #IMPLIED
    typeValeur CDATA #IMPLIED
    valeur CDATA #IMPLIED
    referenceReduction CDATA #IMPLIED
>

=== oussama-denden/tos/opale-api/src/test/resources/dataset/transforme-en-contrat.xml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE dataset SYSTEM "..\dtd\Opale.dtd">
<dataset>

<client id="1000" clientId="1000" adresseId="1000"/>
<client id="1001" clientId="1001" adresseId="1001"/>
<client id="1002" clientId="1002" adresseId="1002"/>

<commande id="1000" canal="welcome" codePartenaire="part_123456" ip="GRC.WEL-JOHNDOE" qui="GRC.WEL-JOHNDOE" ts="[now]" reference="00000004" referenceDraft="00000004" clientAFacturerId="1000" clientALivrerId="1001" clientSouscripteurId="1002"/>

<commandeLigne id="1000" qui="GRC.WEL-JOHNDOE" ts="[now]" gamme="jet" modeFacturation="PREMIER_MOIS" referenceOffre="jet_surf10" commandeId="1000" secteur="sat" tarifId="1006" geste="VENTE"/>

<commandeLigneDetail id="1000" referenceChoix="trafic10g" label="Trafic 10 Gigas" typeProduit="SERVICE" dependDe="1001" commandeLigneId="1000" tarifId="1000"  />
<commandeLigneDetail id="1001" referenceChoix="kitsat" label="Trafic 10 Gigas" typeProduit="BIEN" commandeLigneId="1000" />


<tarif id="1000" duree="5" engagement="12" frequence="4" prix="34.9" reference="mensuel_jet10_base" typeTVA="S" />
<tarif id="1002" duree="5" engagement="12" frequence="4" prix="34.9" reference="annuel_jet10_base" typeTVA="S" />
<tarif id="1004" duree="12" engagement="12" frequence="12" prix="34.9" reference="annuel_jet10_base" typeTVA="S" />
<tarif id="1005" duree="12" engagement="12" frequence="12" prix="34.9" reference="annuel_jet10_base" typeTVA="S" />
<tarif id="1006" duree="12" engagement="12" frequence="12" prix="34.9" reference="annuel_jet10_base" typeTVA="S" />

<frais id="1000" reference="std_Cloture" montant="50" typeFrais="RESILIATION" tarifId="1000" />
<frais id="1002" montant="50" typeFrais="RESILIATION" tarifId="1002" />
<frais id="1003" montant="50" typeFrais="CREATION" tarifId="1003" />
<frais id="1004" montant="50" typeFrais="RESILIATION" tarifId="1004" />
<frais id="1005" montant="50" typeFrais="CREATION" tarifId="1005" />
<frais id="1006" reference="engagement_kitsat" montant="50" typeFrais="RESILIATION" tarifId="1006" />
<frais id="1007" montant="50" typeFrais="RESILIATION" tarifId="1007" />

<paiement id="1001" montant="10" modePaiement="CB" reference="00000001" referenceCommande="00000004" canal="welcome" ip="127.0.0.1" qui="GRC.WEL-JOHNDOE" ts="[now]" typePaiement="RECURRENT" timestampPaiement="[now]" />

<reduction id="1005" label="reduction sur draft" nbUtilisationMax="5" reference="00000001" referenceDraft="00000004" typeValeur="POURCENTAGE" valeur="50" />	
<reduction id="1000" label="reduction sur ligne" nbUtilisationMax="5" reference="00000002" referenceDraft="00000004" referenceLigne="jet_surf10" typeValeur="POURCENTAGE" valeur="50" />
<reduction id="1001" label="reduction sur produit" nbUtilisationMax="5" reference="00000003" referenceDraft="00000004" referenceLigne="jet_surf10" referenceLigneDetail="trafic10g" typeValeur="POURCENTAGE" valeur="50" />
<reduction id="1002" label="reduction sur produit parent" nbUtilisationMax="5" reference="00000004" referenceDraft="00000004" referenceLigne="jet_surf10" referenceTarif="annuel_jet10_base" typeValeur="POURCENTAGE" valeur="50" />
<reduction id="1003" label="reduction sur frais ligne" nbUtilisationMax="5" reference="00000005" referenceDraft="00000004" referenceLigne="jet_surf10" referenceFrais="engagement_kitsat" referenceTarif="annuel_jet10_base" typeValeur="POURCENTAGE" valeur="50" />
<reduction id="1004" label="reduction sur frais detail" nbUtilisationMax="5" reference="00000006" referenceDraft="00000004" referenceLigne="jet_surf10" referenceFrais="std_Cloture" referenceLigneDetail="trafic10g" referenceTarif="mensuel_jet10_base" typeValeur="POURCENTAGE" valeur="50" />
</dataset>

=== oussama-denden/tos/src/test/resources/dataset/is-besoin-paiement-comptant.xml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE dataset SYSTEM "..\dtd\Opale.dtd">
<dataset>
<commande id="1000" canal="welcome"  ip="GRC.WEL-JOHNDOE" timestamp="[now]" reference="00000001" referenceDraft="00000001" />
<commande id="1001" canal="welcome"  ip="GRC.WEL-JOHNDOE" timestamp="[now]" reference="00000002" referenceDraft="00000002" />
<commande id="1002" canal="welcome"  ip="GRC.WEL-JOHNDOE" timestamp="[now]" reference="00000003" referenceDraft="00000003" />

<commandeLigne id="1000" gamme="jet" modeFacturation="PREMIER_MOIS" modePaiement="CB" referenceOffre="jet_surf10" commandeId="1000" famille="sat" tarifId="1002" />
<commandeLigne id="1001" gamme="jet" modeFacturation="PREMIER_MOIS" modePaiement="CB" referenceOffre="jet_surf10" commandeId="1001" famille="sat" tarifId="1006" />
<commandeLigne id="1002" gamme="jet" modeFacturation="PREMIER_MOIS" modePaiement="CB" referenceOffre="jet_surf10" commandeId="1002" famille="sat"/>

<commandeLigneDetail id="1000" modePaiement="CB" referenceChoix="jet" label="Trafic 10 Gigas" typeProduit="SERVICE" dependDe="1001" commandeLigneId="1000" tarifId="1000" />
<commandeLigneDetail id="1001" modePaiement="CB" referenceChoix="kitsat" label="Trafic 10 Gigas" typeProduit="BIEN" commandeLigneId="1000" tarifId="1001" />
<commandeLigneDetail id="1002" modePaiement="CB" referenceChoix="jet" label="Trafic 10 Gigas" typeProduit="SERVICE" dependDe="1003" commandeLigneId="1001" tarifId="1004" />
<commandeLigneDetail id="1003" modePaiement="CB" referenceChoix="kitsat" label="Trafic 10 Gigas" typeProduit="BIEN" commandeLigneId="1001" tarifId="1005" />
<commandeLigneDetail id="1004" modePaiement="CB" referenceChoix="jet" label="Trafic 10 Gigas" typeProduit="SERVICE" dependDe="1003" commandeLigneId="1002" />
<commandeLigneDetail id="1005" modePaiement="CB" referenceChoix="kitsat" label="Trafic 10 Gigas" typeProduit="BIEN" commandeLigneId="1002" />

<tarif id="1000" duree="5" engagement="12" frequence="5" prix="34.9" reference="annuel_jet10_base" typeTVA="S" />
<tarif id="1001" duree="12" engagement="12" frequence="12" prix="34.9" reference="annuel_jet10_base" typeTVA="S" />
<tarif id="1002" duree="12" engagement="12" frequence="12" prix="34.9" reference="annuel_jet10_base" typeTVA="S" />
<tarif id="1004" duree="5" engagement="12" frequence="5" prix="34.9" reference="annuel_jet10_base" typeTVA="S" />
<tarif id="1005" duree="12" engagement="12" frequence="6" prix="34.9" reference="annuel_jet10_base" typeTVA="S" />
<tarif id="1006" duree="12" engagement="12" frequence="5" prix="34.9" reference="annuel_jet10_base" typeTVA="S" />

<frais id="1000" montant="50" typeTVA="S" typeFrais="CREATION" tarifId="1000" />
<frais id="1001" montant="50" typeTVA="S" typeFrais="RESILIATION" tarifId="1001" />
<frais id="1002" montant="50" typeTVA="S" typeFrais="RESILIATION" tarifId="1002" />
<frais id="1004" montant="50" typeTVA="S" typeFrais="RESILIATION" tarifId="1004" />
<frais id="1005" montant="50" typeTVA="S" typeFrais="CREATION" tarifId="1005" />
<frais id="1006" montant="50" typeTVA="S" typeFrais="RESILIATION" tarifId="1006" />

<paiement id="1000" montant="90" modePaiement="CB" reference="00000001" referenceCommande="00000001" typePaiement="COMPTANT" canal="welcome" ip="127.0.0.1" qui="GRC.WEL-JOHNDOE" timestamp="[now]" timestampIntention="[now]" timestampPaiement="[now]"  />
<paiement id="1001" montant="150" modePaiement="CB" reference="00000001" referenceCommande="00000002" typePaiement="COMPTANT" canal="welcome" ip="127.0.0.1" qui="GRC.WEL-JOHNDOE" timestamp="[now]" timestampPaiement="[now]"  />
<paiement id="1002" montant="90" modePaiement="CB" reference="00000001" referenceCommande="00000003" typePaiement="RECURRENT" canal="welcome" ip="127.0.0.1" qui="GRC.WEL-JOHNDOE" timestamp="[now]" timestampPaiement="[now]"  />
</dataset>

=== oussama-denden/tos/opale-api/src/test/resources/dataset/transformer-en-commande.xml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE dataset SYSTEM "..\dtd\Opale.dtd">

<dataset>
	<keygen />
	<draft />
	<draft id="1" reference="REF-DRAFT-1" codePartenaire="000111"
		timestamp="[now]" />
	<draft id="2" reference="REF-DRAFT-3" codePartenaire="000111"
		timestamp="[now]" />

	<draft id="3" reference="REF-DRAFT-4" codePartenaire="000111"
		timestamp="[now]" />
	<draftLigne />
	<draftLigne id="1000" reference="00000001" referenceTarif="mensuel_jet10_base"
		referenceOffre="jet_surf10" qui="GRC.WEL-JOHNDOE"
		canal="Welcome" ip="127.0.0.1" timestamp="[now]" draftId="1" geste="VENTE"/>

	<draftLigne id="1001" reference="00000002" referenceTarif="mensuel_jet10_base"
		referenceOffre="jet_surf100" qui="GRC.WEL-JOHNDOE"
		canal="Welcome" ip="127.0.0.1" timestamp="[now]" draftId="2" geste="VENTE"/>

	<draftLigne id="1002" reference="00000003" referenceTarif="mensuel_jet10_base"
		referenceOffre="jet_surf10" qui="GRC.WEL-JOHNDOE"
		canal="Welcome" ip="127.0.0.1" timestamp="[now]" draftId="3" geste="VENTE"/>

	<draftLigneDetail />
	<draftLigneDetail id="1000" referenceSelection="kitsat"
		referenceChoix="trafic10g" referenceTarif="mensuel_jet10_base"
		configurationJson="" draftLigneId="1000" />
	<draftLigneDetail id="1001" referenceSelection="jet"
		referenceChoix="trafic10g" referenceTarif="mensuel_jet10_base"
		configurationJson="" draftLigneId="1000" dependDe="1000" />

	<draftLigneDetail id="1002" referenceSelection="kitsat"
		referenceChoix="trafic10g" referenceTarif="mensuel_jet10_base"
		configurationJson="" draftLigneId="1001" />
	<draftLigneDetail id="1003" referenceSelection="jet"
		referenceChoix="trafic10g" referenceTarif="mensuel_jet10_base"
		configurationJson="" draftLigneId="1001" dependDe="1000" />

	<draftLigneDetail id="1004" referenceSelection="kitsat10"
		referenceChoix="trafic10g" referenceTarif="mensuel_jet10_base"
		configurationJson="" draftLigneId="1002" />

	<reduction id="1005" label="reduction sur ligne"
		nbUtilisationMax="5" reference="00000001" referenceDraft="REF-DRAFT-1"
		typeValeur="POURCENTAGE" valeur="50" />
	<reduction id="1000" label="reduction sur ligne"
		nbUtilisationMax="5" reference="00000002" referenceDraft="REF-DRAFT-1"
		referenceLigne="00000001" typeValeur="POURCENTAGE" valeur="50" />
	<reduction id="1001" label="reduction sur produit"
		nbUtilisationMax="5" reference="00000003" referenceDraft="REF-DRAFT-1"
		referenceLigne="00000001" referenceLigneDetail="trafic10g" typeValeur="POURCENTAGE"
		valeur="50" />
	<reduction id="1002" label="reduction sur produit parent"
		nbUtilisationMax="5" reference="00000004" referenceDraft="REF-DRAFT-1"
		referenceLigne="00000001" referenceTarif="annuel_jet10_base"
		typeValeur="POURCENTAGE" valeur="50" />
	<reduction id="1003" label="reduction sur frais ligne"
		nbUtilisationMax="5" reference="00000005" referenceDraft="REF-DRAFT-1"
		referenceLigne="00000001" referenceFrais="engagement_kitsat"
		referenceTarif="annuel_jet10_base" typeValeur="POURCENTAGE" valeur="50" />
	<reduction id="1004" label="reduction sur frais detail"
		nbUtilisationMax="5" reference="00000006" referenceDraft="REF-DRAFT-1"
		referenceLigne="00000001" referenceFrais="std_Cloture"
		referenceLigneDetail="trafic10g" referenceTarif="mensuel_jet10_base"
		typeValeur="POURCENTAGE" valeur="50" />

</dataset>

=== oussama-denden/tos/opale-api/src/test/resources/dataset/valider-draft.xml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE dataset SYSTEM ".\src\test\resources\dtd\opale.dtd">

<dataset>
	<client id="1" clientId="client-1245" adresseId="Adr_Facturation_1" />
	<client id="2" clientId="client-1245" adresseId="Adr_Souscripteur_1" />
	<client id="3" clientId="client-1245" adresseId="Adr_Livraison_1" />
	<draft id="1" reference="REF-DRAFT-1" codePartenaire="000111"
		ts="[now]" clientAFacturerId="1" clientALivrerId="3"
		clientSouscripteurId="2" annulerCommandeSource="false"/>
	<draft id="2" reference="REF-DRAFT-3" codePartenaire="000111"
		ts="[now]" annulerCommandeSource="false"/>
	<draft id="3" reference="REF-DRAFT-4" codePartenaire="000111"
		ts="[now]" annulerCommandeSource="false"/>
	<draft id="4" reference="REF-DRAFT-5" codePartenaire="000111"
		ts="[now]" clientAFacturerId="1" clientALivrerId="3"
		clientSouscripteurId="2" annulerCommandeSource="false"/>
	<draft id="5" reference="REF-DRAFT-6" codePartenaire="000111"
		ts="[now]" clientAFacturerId="1" clientALivrerId="3"
		clientSouscripteurId="2" annulerCommandeSource="false"/>
	<draft id="6" reference="REF-DRAFT-7" codePartenaire="000111"
		ts="[now]" clientAFacturerId="1" clientALivrerId="3"
		clientSouscripteurId="2" annulerCommandeSource="false"/>

	<draftLigne id="1000" reference="00000001" referenceTarif="mensuel_jet10_base"
		referenceOffre="jet_surf10" qui="GRC.WEL-JOHNDOE"
		canal="Welcome" ip="127.0.0.1" ts="[now]" draftId="1" />
	<draftLigne id="1001" reference="00000002" referenceTarif="mensuel_jet10_base"
		referenceOffre="jet_surf100" qui="GRC.WEL-JOHNDOE"
		canal="Welcome" ip="127.0.0.1" ts="[now]" draftId="2" />
	<draftLigne id="1002" reference="00000003" referenceTarif="mensuel_jet10_base"
		referenceOffre="jet_surf10" qui="GRC.WEL-JOHNDOE"
		canal="Welcome" ip="127.0.0.1" ts="[now]" draftId="3" />
	<draftLigne id="1003" reference="00000001" referenceTarif="mensuel_jet10_base10"
		referenceOffre="jet_surf10" qui="GRC.WEL-JOHNDOE"
		canal="Welcome" ip="127.0.0.1" ts="[now]" draftId="4" />
	<draftLigne id="1004" reference="00000001" referenceTarif="mensuel_jet10_base"
		referenceOffre="jet_surf10" qui="GRC.WEL-JOHNDOE"
		canal="Welcome" ip="127.0.0.1" ts="[now]" draftId="5" />
	<draftLigne id="1005" reference="00000001" referenceTarif="mensuel_jet10_base"
		referenceOffre="jet_surf10" qui="GRC.WEL-JOHNDOE"
		canal="Welcome" ip="127.0.0.1" ts="[now]" draftId="6" />

	<draftLigneDetail id="1000" referenceSelection="kitsat"
		referenceChoix="trafic10g" referenceTarif="annuel_jet10_base"
		configurationJson="" draftLigneId="1000" />
	<draftLigneDetail id="1001" referenceSelection="jet"
		referenceChoix="trafic10g" referenceTarif="annuel_jet10_base"
		configurationJson="" draftLigneId="1000" dependDe="1000" />
	<draftLigneDetail id="1002" referenceSelection="kitsat"
		referenceChoix="trafic10g" referenceTarif="achat_kit_mensuel"
		configurationJson="" draftLigneId="1001" />
	<draftLigneDetail id="1003" referenceSelection="jet"
		referenceChoix="trafic10g" referenceTarif="achat_kit_mensuel"
		configurationJson="" draftLigneId="1001" dependDe="1000" />
	<draftLigneDetail id="1004" referenceSelection="kitsat10"
		referenceChoix="trafic10g" referenceTarif="annuel_jet10_base"
		configurationJson="" draftLigneId="1002" />
	<draftLigneDetail id="1005" referenceSelection="kitsat"
		referenceChoix="trafic10g" referenceTarif="annuel_jet10_base"
		configurationJson="" draftLigneId="1003" />
	<draftLigneDetail id="1006" referenceSelection="jet"
		referenceChoix="trafic10g" referenceTarif="annuel_jet10_base"
		configurationJson="" draftLigneId="1003" dependDe="1005" />
	<draftLigneDetail id="1007" referenceSelection="kitsat"
		referenceChoix="trafic10g" referenceTarif="annuel_jet10_base"
		configurationJson="" draftLigneId="1004" />
	<draftLigneDetail id="1008" referenceSelection="jet"
		referenceChoix="trafic10g" referenceTarif="annuel_jet10_base10"
		configurationJson="" draftLigneId="1004" dependDe="1007" />
	<draftLigneDetail id="1009" referenceSelection="kitsat"
		referenceChoix="trafic100g" referenceTarif="annuel_jet10_base"
		configurationJson="" draftLigneId="1005" />
	<draftLigneDetail id="1010" referenceSelection="jet"
		referenceChoix="trafic10g" referenceTarif="annuel_jet10_base"
		configurationJson="" draftLigneId="1005" dependDe="1009" />

</dataset>

=== oussama-denden/tos/src/test/resources/dataset/calculer-cout-draft-reduction.xml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE dataset SYSTEM "..\dtd\Opale.dtd">

<dataset>
<draft id="1000" canal="welcome" codePartenaire="PART_CODE" ip="127.0.0.1" qui="GRC.WEL-JOHNDOE" timestamp="[now]" reference="Dra-00000001" geste="VENTE" />
<draft id="1001" canal="welcome" codePartenaire="PART_CODE" ip="127.0.0.1" qui="GRC.WEL-JOHNDOE" timestamp="[now]" reference="Dra-00000002" geste="VENTE" />

<draftLigne id="1000" canal="welcome" ip="127.0.0.1" qui="GRC.WEL-JOHNDOE" timestamp="[now]" reference="00000001" referenceOffre="jet_surf10" referenceTarif="annuel_jet10_base" draftId="1000" />
<draftLigne id="1001" canal="welcome" ip="127.0.0.1" qui="GRC.WEL-JOHNDOE" timestamp="[now]" reference="00000001" referenceOffre="jet_surf10" referenceTarif="annuel_jet10_base" draftId="1001" />

<draftLigneDetail id="1000" referenceChoix="kitsat" referenceSelection="kitsat" referenceTarif="mensuel_jet10_base" draftLigneId="1000" />
<draftLigneDetail id="1001" referenceChoix="jet" referenceSelection="jet" referenceTarif="mensuel_jet10_base" dependDe="1000" draftLigneId="1000" />
<draftLigneDetail id="1002" referenceChoix="jet" referenceSelection="kitsat" referenceTarif="mensuel_jet10_base" draftLigneId="1001" />
<draftLigneDetail id="1003" referenceChoix="kitsat" referenceSelection="kitTlf" referenceTarif="mensuel_jet10_base" dependDe="1002" draftLigneId="1001" />

<tarif id="1000" duree="5" engagement="12" frequence="5" prix="34.9" reference="annuel_jet10_base" typeTVA="S" />
<tarif id="1001" duree="12" engagement="12" frequence="5" prix="34.9" reference="annuel_jet10_base" typeTVA="S" />
<tarif id="1002" duree="12" engagement="12" frequence="6" prix="34.9" reference="annuel_jet10_base" typeTVA="S" />

<reduction id="1000" reference="reduc-draft" referenceDraft="Dra-00000001" typeValeur="POURCENTAGE" valeur="10"/>
<reduction id="1001" reference="reduc-ligne" referenceDraft="Dra-00000001" referenceLigne="00000001" typeValeur="POURCENTAGE" valeur="10"/>
<reduction id="1002" reference="reduc-ligne-detail-kitsat" referenceDraft="Dra-00000001" referenceLigne="00000001" referenceLigneDetail="kitsat" typeValeur="POURCENTAGE" valeur="10"/>
<reduction id="1003" reference="reduc-ligne-detail-jet" referenceDraft="Dra-00000001" referenceLigne="00000001" referenceLigneDetail="jet" typeValeur="POURCENTAGE" valeur="10"/>
<reduction id="1004" reference="reduc-ligne-frais" referenceDraft="Dra-00000001" referenceLigne="00000001"  referenceTarif="annuel_jet10_base"  referenceFrais="engagement_kitsat" typeValeur="POURCENTAGE" valeur="10"/>
<reduction id="1005" reference="reduc-ligne-detail-jet-frais" referenceDraft="Dra-00000001" referenceLigne="00000001" referenceLigneDetail="jet"  referenceTarif="mensuel_jet10_base"  referenceFrais="engagement_kitsat" typeValeur="POURCENTAGE" valeur="10"/>
<reduction id="1006" reference="reduc-ligne-detail-kitsat-frais" referenceDraft="Dra-00000001" referenceLigne="00000001" referenceLigneDetail="kitsat"  referenceTarif="mensuel_jet10_base"  referenceFrais="engagement_kitsat" typeValeur="POURCENTAGE" valeur="10"/>

</dataset>

=== oussama-denden/tos/opale-api/src/test/resources/dataset/ajout-reduction.xml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE dataset SYSTEM "./src/test/resources/dtd/opale.dtd">

<dataset>
<draft id="1" reference="REF-DRAFT-1"   codePartenaire="000111" ts="[now]" canal="welcome" qui="someone" annulerCommandeSource="false"/>
<draft id="2" reference="REF-DRAFT-2"   codePartenaire="000222" ts="[now]" canal="welcome" qui="someone" annulerCommandeSource="false"/>
<draft id="3" reference="REF-DRAFT-3"   codePartenaire="000222" ts="[now]" canal="welcome" qui="someone" annulerCommandeSource="false"/>

<draftLigne id="3" reference="REF-LIGNE-1" canal="welcome" ip="127.0.0.1" qui="GRC.WEL-JOHNDOE" ts="[now]" referenceOffre="jet_surf10" referenceTarif="annuel_jet10_base" draftId="1" />
<draftLigne id="4" reference="REF-LIGNE-2" canal="welcome" ip="127.0.0.1" qui="GRC.WEL-JOHNDOE" ts="[now]" referenceOffre="jet_surf10"  draftId="1" />

<draftLigneDetail id="5" referenceChoix="kitsat" referenceSelection="kitsat" referenceTarif="mensuel_jet10_base" draftLigneId="3" />
<draftLigneDetail id="6" referenceChoix="jet" referenceSelection="jet"  dependDe="5" draftLigneId="3" />

<reduction id="7" reference="reduc-draft" referenceDraft="REF-DRAFT-3" typeValeur="POURCENTAGE" valeur="10"/>

</dataset>

=== oussama-denden/tos/opale-api/src/test/resources/dataset/is-besoin-paiement-recurrent.xml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE dataset SYSTEM "..\dtd\Opale.dtd">
<dataset>
<commande id="1000" canal="welcome"  ip="GRC.WEL-JOHNDOE" timestamp="[now]" reference="00000001" referenceDraft="00000001" />
<commande id="1001" canal="welcome"  ip="GRC.WEL-JOHNDOE" timestamp="[now]" reference="00000002" referenceDraft="00000002" />
<commande id="1002" canal="welcome"  ip="GRC.WEL-JOHNDOE" timestamp="[now]" reference="00000003" referenceDraft="00000003" />

<commandeLigne id="1000" gamme="jet" modeFacturation="PREMIER_MOIS" referenceOffre="jet_surf10" commandeId="1000" secteur="sat" tarifId="1002" />
<commandeLigne id="1001" gamme="jet" modeFacturation="PREMIER_MOIS" referenceOffre="jet_surf10" commandeId="1001" secteur="sat" tarifId="1006" />
<commandeLigne id="1002" gamme="jet" modeFacturation="PREMIER_MOIS" referenceOffre="jet_surf10" commandeId="1002" secteur="sat" tarifId="1007" />

<commandeLigneDetail id="1000" referenceChoix="jet" label="Trafic 10 Gigas" typeProduit="SERVICE" dependDe="1001" commandeLigneId="1000" tarifId="1000" />
<commandeLigneDetail id="1001" referenceChoix="kitsat" label="Trafic 10 Gigas" typeProduit="BIEN" commandeLigneId="1000" tarifId="1001" />
<commandeLigneDetail id="1002" referenceChoix="jet" label="Trafic 10 Gigas" typeProduit="SERVICE" dependDe="1003" commandeLigneId="1001" tarifId="1004" />
<commandeLigneDetail id="1003" referenceChoix="kitsat" label="Trafic 10 Gigas" typeProduit="BIEN" commandeLigneId="1001" tarifId="1005" />
<commandeLigneDetail id="1004" referenceChoix="jet" label="Trafic 10 Gigas" typeProduit="SERVICE" dependDe="1003" commandeLigneId="1002" tarifId="1008" />
<commandeLigneDetail id="1005" referenceChoix="kitsat" label="Trafic 10 Gigas" typeProduit="BIEN" commandeLigneId="1002" tarifId="1009" />

<tarif id="1000" duree="5" engagement="12" frequence="5" prix="34.9" reference="annuel_jet10_base" typeTVA="S" />
<tarif id="1001" duree="12" engagement="12" frequence="12" prix="34.9" reference="annuel_jet10_base" typeTVA="S" />
<tarif id="1002" duree="12" engagement="12" frequence="12" prix="34.9" reference="annuel_jet10_base" typeTVA="S" />
<tarif id="1004" duree="5" engagement="12" frequence="5" prix="34.9" reference="annuel_jet10_base" typeTVA="S" />
<tarif id="1005" duree="12" engagement="12" frequence="6" prix="34.9" reference="annuel_jet10_base" typeTVA="S" />
<tarif id="1006" duree="12" engagement="12" frequence="5" prix="34.9" reference="annuel_jet10_base" typeTVA="S" />
<tarif id="1007" duree="5" engagement="12" frequence="5" prix="34.9" reference="annuel_jet10_base" typeTVA="S" />
<tarif id="1008" duree="12" engagement="12" frequence="6" prix="34.9" reference="annuel_jet10_base" typeTVA="S" />
<tarif id="1009" duree="12" engagement="12" frequence="5" prix="34.9" reference="annuel_jet10_base" typeTVA="S" />

<frais id="1000" montant="50" typeFrais="CREATION" tarifId="1000" />
<frais id="1001" montant="50" typeFrais="RESILIATION" tarifId="1001" />
<frais id="1002" montant="50" typeFrais="RESILIATION" tarifId="1002" />
<frais id="1004" montant="50" typeFrais="RESILIATION" tarifId="1004" />
<frais id="1005" montant="50" typeFrais="CREATION" tarifId="1005" />
<frais id="1006" montant="50" typeFrais="RESILIATION" tarifId="1006" />
<frais id="1007" montant="50" typeFrais="RESILIATION" tarifId="1007" />
<frais id="1008" montant="50" typeFrais="CREATION" tarifId="1008" />
<frais id="1009" montant="50" typeFrais="RESILIATION" tarifId="1009" />

<paiement id="1000" montant="90" modePaiement="CB" reference="00000001" referenceCommande="00000001" typePaiement="COMPTANT" canal="welcome" ip="127.0.0.1" qui="GRC.WEL-JOHNDOE" timestamp="[now]" timestampIntention="[now]" timestampPaiement="[now]"  />
<paiement id="1001" montant="90" modePaiement="CB" reference="00000001" referenceCommande="00000003" typePaiement="RECURRENT" canal="welcome" ip="127.0.0.1" qui="GRC.WEL-JOHNDOE" timestamp="[now]" timestampPaiement="[now]"  />
</dataset>
