=== oussama-denden/tos/opale-api/src/test/resources/dtd/Opale.dtd
<!ELEMENT dataset (keygen*,client*,draft*, draftLigne*, draftLigneDetail*, commande*, commandeLigne*, commandeLigneDetail*, tarif*, frais*,signature*,paiement*,reduction*)>

<!ELEMENT draft EMPTY>
<!ATTLIST draft
    id CDATA #IMPLIED
    reference CDATA #IMPLIED
    clientAFacturerId CDATA #IMPLIED
    clientALivrerId CDATA #IMPLIED
    clientSouscripteurId CDATA #IMPLIED
    codePartenaire CDATA #IMPLIED
    qui CDATA #IMPLIED
    ip CDATA #IMPLIED
    canal CDATA #IMPLIED
    timestamp CDATA #IMPLIED
    referenceExterne CDATA #IMPLIED
    dateAnnulation  CDATA #IMPLIED
>
<!ELEMENT draftLigne EMPTY>
<!ATTLIST draftLigne
    id CDATA #IMPLIED
    reference CDATA #IMPLIED
    referenceTarif CDATA #IMPLIED
    dateCreation CDATA #IMPLIED
    qui CDATA #IMPLIED
    ip CDATA #IMPLIED
    canal CDATA #IMPLIED
    timestamp CDATA #IMPLIED
    draftId CDATA #IMPLIED
    referenceOffre CDATA #IMPLIED
     geste CDATA #IMPLIED
>
<!ELEMENT draftLigneDetail EMPTY>
<!ATTLIST draftLigneDetail
     id CDATA #IMPLIED
    referenceSelection CDATA #IMPLIED
    referenceChoix CDATA #IMPLIED
    referenceTarif CDATA #IMPLIED
    configurationJson CDATA #IMPLIED
    dependDe CDATA #IMPLIED
    draftLigneId CDATA #IMPLIED
>

<!ELEMENT tracage EMPTY>
<!ATTLIST tracage
     id CDATA #IMPLIED
    referenceDraft CDATA #IMPLIED
    action CDATA #IMPLIED
    user CDATA #IMPLIED
    date CDATA #IMPLIED
>

<!ELEMENT keygen EMPTY>
<!ATTLIST keygen
     id CDATA #IMPLIED
    referenceDraft CDATA #IMPLIED
    entite CDATA #IMPLIED
    prefix CDATA #IMPLIED
>

<!ELEMENT client EMPTY>
<!ATTLIST client
     id CDATA #IMPLIED
    adresseId CDATA #IMPLIED
    clientId CDATA #IMPLIED
    canal CDATA #IMPLIED
  ip  CDATA #IMPLIED
  qui  CDATA #IMPLIED
  timestamp  CDATA #IMPLIED
  tva CDATA #IMPLIED
>

<!ELEMENT commande EMPTY>
<!ATTLIST commande
    id CDATA #IMPLIED
    reference CDATA #IMPLIED
    referenceDraft CDATA #IMPLIED
    clientAFacturerId CDATA #IMPLIED
    clientALivrerId CDATA #IMPLIED
    clientSouscripteurId CDATA #IMPLIED
    dateCreation CDATA #IMPLIED
    dateTransformationContrat CDATA #IMPLIED
    dateAnnulation CDATA #IMPLIED
    qui CDATA #IMPLIED
    ip CDATA #IMPLIED
    canal CDATA #IMPLIED
    timestamp CDATA #IMPLIED
    codePartenaire CDATA #IMPLIED
   
>

<!ELEMENT commandeLigne EMPTY>
<!ATTLIST commandeLigne
    id CDATA #IMPLIED
    dateCreation CDATA #IMPLIED
    qui CDATA #IMPLIED
    ip CDATA #IMPLIED
    canal CDATA #IMPLIED
    timestamp CDATA #IMPLIED
    gamme CDATA #IMPLIED
    label CDATA #IMPLIED
    modeFacturation CDATA #IMPLIED
    typeProduit CDATA #IMPLIED
    referenceOffre CDATA #IMPLIED
    referenceContrat CDATA #IMPLIED
    secteur CDATA #IMPLIED
    commandeId CDATA #IMPLIED
    tarifId CDATA #IMPLIED
    geste CDATA #IMPLIED
>

<!ELEMENT commandeLigneDetail EMPTY>
<!ATTLIST commandeLigneDetail
    id CDATA #IMPLIED
    configurationJson CDATA #IMPLIED
    referenceSelection CDATA #IMPLIED
    referenceChoix CDATA #IMPLIED
    label CDATA #IMPLIED
    typeProduit CDATA #IMPLIED
    dependDe CDATA #IMPLIED
    commandeLigneId CDATA #IMPLIED
    tarifId CDATA #IMPLIED
>

<!ELEMENT tarif EMPTY>
<!ATTLIST tarif
     id CDATA #IMPLIED
    duree CDATA #IMPLIED
    engagement CDATA #IMPLIED
    frequence CDATA #IMPLIED
    prix CDATA #IMPLIED
    reference CDATA #IMPLIED
    typeTVA CDATA #IMPLIED
>

<!ELEMENT frais EMPTY>
<!ATTLIST frais
     id CDATA #IMPLIED
    label CDATA #IMPLIED
    montant CDATA #IMPLIED
    politique CDATA #IMPLIED
    politiqueIndex CDATA #IMPLIED
    reference CDATA #IMPLIED
    typeFrais CDATA #IMPLIED
    tarifId CDATA #IMPLIED
>

<!ELEMENT signature EMPTY>
<!ATTLIST signature
    id CDATA #IMPLIED
    reference CDATA #IMPLIED
    mode CDATA #IMPLIED
    timestampSignature CDATA #IMPLIED
    footprint CDATA #IMPLIED
    idSignature  CDATA #IMPLIED
    qui CDATA #IMPLIED
    ip CDATA #IMPLIED
    canal CDATA #IMPLIED
    timestamp CDATA #IMPLIED
    referenceCommande CDATA #IMPLIED
    dateAnnulation  CDATA #IMPLIED
    timestampIntention CDATA #IMPLIED
    dateCreation CDATA #IMPLIED
>

<!ELEMENT paiement EMPTY>
<!ATTLIST paiement
    id CDATA #IMPLIED
    infoPaiement CDATA #IMPLIED
    modePaiement CDATA #IMPLIED
    montant CDATA #IMPLIED
    reference CDATA #IMPLIED
    referenceCommande CDATA #IMPLIED
    qui CDATA #IMPLIED
    ip CDATA #IMPLIED
    canal CDATA #IMPLIED
    timestamp CDATA #IMPLIED
    timestampIntention CDATA #IMPLIED
    timestampPaiement CDATA #IMPLIED
    typePaiement CDATA #IMPLIED
    dateCreation CDATA #IMPLIED
>

<!ELEMENT reduction EMPTY>
<!ATTLIST reduction
    id CDATA #IMPLIED
    dateDebut CDATA #IMPLIED
    dateFin CDATA #IMPLIED
    label CDATA #IMPLIED
    nbUtilisationMax CDATA #IMPLIED
    reference CDATA #IMPLIED
    referenceDraft CDATA #IMPLIED
    referenceFrais CDATA #IMPLIED
    referenceLigne CDATA #IMPLIED
    referenceLigneDetail CDATA #IMPLIED
    referenceTarif CDATA #IMPLIED
    typeValeur CDATA #IMPLIED
    valeur CDATA #IMPLIED
    referenceReduction CDATA #IMPLIED
>

=== oussama-denden/tos/opale-api/src/test/resources/dataset/signer-commande.xml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE dataset SYSTEM "..\dtd\Opale.dtd">

<dataset>


<commande id="1"  reference="REF-COMMANDE-1" ts="[now]"/>

<commande id="2"  reference="REF-COMMANDE-2" ts="[now]" />

<commande id="3"  reference="REF-COMMANDE-3" ts="[now]" />

<commande id="4"  reference="REF-COMMANDE-4" ts="[now]" />

<commande id="7"  reference="REF-COMMANDE-5" ts="[now]" />

<commande id="10"  reference="REF-COMMANDE-6" ts="[now]" />

<commande id="11"  reference="REF-COMMANDE-7" ts="[now]" />

<signature id="1"  reference="REF-SIGNATURE-1" mode="OPEN_TRUST" canal="welcome" ip="127.0.0.1" qui="GRC.WEL-JOHNDOE" ts="[now]"  referenceCommande="REF-COMMANDE-2" />
<signature id="2"  reference="REF-SIGNATURE-2" mode="OPEN_TRUST" idSignature="opentrust_dfr2225tr3555" timestampSignature="[now]" footprint="e2680542f77606f42f1cb06d6" canal="welcome" ip="127.0.0.1" qui="GRC.WEL-JOHNDOE" ts="[now]"  referenceCommande="REF-COMMANDE-4"/>


<signature id="3"  reference="REF-SIGNATURE-3" mode="OPEN_TRUST" canal="welcome" ip="127.0.0.1" qui="GRC.WEL-JOHNDOE" ts="[now]"  referenceCommande="REF-COMMANDE-6" />
<signature id="4"  reference="REF-SIGNATURE-4" mode="OPEN_TRUST" idSignature="opentrust_dfr2225tr3555" timestampSignature="[now]" footprint="e2680542f77606f42f1cb06d6" canal="welcome" ip="127.0.0.1" qui="GRC.WEL-JOHNDOE" ts="[now]"  referenceCommande="REF-COMMANDE-5"/>

<signature id="8"  reference="REF-SIGNATURE-7" mode="OPEN_TRUST" idSignature="opentrust_dfr2225tr3555" timestampSignature="[now]" footprint="e2680542f77606f42f1cb06d6" canal="welcome" ip="127.0.0.1" qui="GRC.WEL-JOHNDOE" ts="[now]"  referenceCommande="REF-COMMANDE-7"/>
<signature id="5"  reference="REF-SIGNATURE-8" mode="OPEN_TRUST" idSignature="opentrust_dfr2225tr3555" timestampSignature="[now]" footprint="e2680542f77606f42f1cb06d6" canal="welcome" ip="127.0.0.1" qui="GRC.WEL-JOHNDOE" ts="[now]"  referenceCommande="REF-COMMANDE-7" dateAnnulation="[now]"/>
<signature id="6"  reference="REF-SIGNATURE-9" mode="OPEN_TRUST" idSignature="opentrust_dfr2225tr3555" timestampSignature="[now]" footprint="e2680542f77606f42f1cb06d6" canal="welcome" ip="127.0.0.1" qui="GRC.WEL-JOHNDOE" ts="[now]"  referenceCommande="REF-COMMANDE-7" dateAnnulation="[now]"/>

</dataset>

=== oussama-denden/tos/opale-api/src/test/resources/dataset/calculer-cout-draft-reduction.xml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE dataset SYSTEM "..\dtd\Opale.dtd">

<dataset>

<draft/>
<draft id="1000" canal="welcome" codePartenaire="PART_CODE" ip="127.0.0.1" qui="GRC.WEL-JOHNDOE" ts="[now]" reference="Dra-00000001"  />
<draft id="1001" canal="welcome" codePartenaire="PART_CODE" ip="127.0.0.1" qui="GRC.WEL-JOHNDOE" ts="[now]" reference="Dra-00000002"  />

<draftLigne/>
<draftLigne id="1000" canal="welcome" ip="127.0.0.1" qui="GRC.WEL-JOHNDOE" ts="[now]" reference="00000001" referenceOffre="avfwpro-confort-s" referenceTarif="avfw.essentiel.3mois" draftId="1000" />
<draftLigne id="1001" canal="welcome" ip="127.0.0.1" qui="GRC.WEL-JOHNDOE" ts="[now]" reference="00000001" referenceOffre="jet_surf10" referenceTarif="annuel_jet10_base" draftId="1001" />

<draftLigneDetail/>

<reduction/>
<reduction id="1000" reference="reduc-draft" referenceDraft="Dra-00000001" typeValeur="POURCENTAGE" valeur="10"/>
<reduction id="1001" reference="reduc-ligne" referenceDraft="Dra-00000001" referenceLigne="00000001" typeValeur="POURCENTAGE" valeur="10"/>
<reduction id="1003" reference="reduc-ligne-tarif" referenceDraft="Dra-00000001" referenceLigne="00000001" referenceTarif="avfw.essentiel.3mois" typeValeur="POURCENTAGE" valeur="10"/>
<reduction id="1004" reference="reduc-ligne-frais" referenceDraft="Dra-00000001" referenceLigne="00000001"  referenceTarif="avfw.essentiel.3mois"  referenceFrais="engagement_kitsat" typeValeur="POURCENTAGE" valeur="10"/>

</dataset>

=== oussama-denden/tos/src/test/resources/dataset/calculer-cout-commande.xml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE dataset SYSTEM "..\dtd\Opale.dtd">

<dataset>

<commande id="1000" canal="welcome"  ip="GRC.WEL-JOHNDOE" timestamp="[now]" reference="Cmd-00000001" referenceDraft="00000001" />

<commandeLigne id="1000" gamme="jet" modeFacturation="PREMIER_MOIS" modePaiement="CB" referenceOffre="jet_surf10" commandeId="1000" famille="sat" tarifId="1002" />

<commandeLigneDetail id="1000" modePaiement="CB" referenceChoix="jet" label="Trafic 10 Gigas" typeProduit="SERVICE" dependDe="1001" commandeLigneId="1000" tarifId="1000" />
<commandeLigneDetail id="1001" modePaiement="CB" referenceChoix="kitsat" label="Trafic 10 Gigas" typeProduit="BIEN" commandeLigneId="1000" tarifId="1001" />

<tarif id="1000" duree="1" engagement="12" frequence="1" prix="34.9" reference="annuel_jet10_base" typeTVA="S" />
<tarif id="1001" duree="1" engagement="12" frequence="1" prix="34.9" reference="annuel_jet10_base" typeTVA="S" />
<tarif id="1002" duree="12" engagement="12" frequence="1" prix="34.9" reference="annuel_jet10_base" typeTVA="S" />

<frais id="1000" montant="50" typeTVA="S" typeFrais="CREATION" tarifId="1002" />
<frais id="1001" montant="50" typeTVA="S" typeFrais="RESILIATION" tarifId="1001" />
<frais id="1002" montant="50" typeTVA="S" typeFrais="RESILIATION" tarifId="1000" />

</dataset>

=== oussama-denden/tos/src/test/resources/dataset/calculer-cout-draft.xml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE dataset SYSTEM "..\dtd\Opale.dtd">

<dataset>
<draft id="1000" canal="welcome" codePartenaire="PART_CODE" ip="127.0.0.1" qui="GRC.WEL-JOHNDOE" timestamp="[now]" reference="Dra-00000001" geste="VENTE" />
<draft id="1001" canal="welcome" codePartenaire="PART_CODE" ip="127.0.0.1" qui="GRC.WEL-JOHNDOE" timestamp="[now]" reference="Dra-00000002" geste="VENTE" />

<draftLigne id="1000" canal="welcome" ip="127.0.0.1" qui="GRC.WEL-JOHNDOE" timestamp="[now]" modePaiement="CB" reference="00000001" referenceOffre="jet_surf10" referenceTarif="annuel_jet10_base" draftId="1000" />
<draftLigne id="1001" canal="welcome" ip="127.0.0.1" qui="GRC.WEL-JOHNDOE" timestamp="[now]" modePaiement="CB" reference="00000001" referenceOffre="jet_surf10" referenceTarif="annuel_jet10_base" draftId="1001" />

<draftLigneDetail id="1000" modePaiement="CB" referenceChoix="kitsat" referenceSelection="kitsat" referenceTarif="mensuel_jet10_base" draftLigneId="1000" />
<draftLigneDetail id="1001" modePaiement="CB" referenceChoix="jet" referenceSelection="jet" referenceTarif="mensuel_jet10_base" dependDe="1000" draftLigneId="1000" />
<draftLigneDetail id="1002" modePaiement="CB" referenceChoix="trafic10g" referenceSelection="kitsat" referenceTarif="mensuel_jet10_base" draftLigneId="1001" />
<draftLigneDetail id="1003" modePaiement="CB" referenceChoix="trafic10g" referenceSelection="kitTlf" referenceTarif="mensuel_jet10_base" dependDe="1002" draftLigneId="1001" />

<tarif id="1000" duree="5" engagement="12" frequence="5" prix="34.9" reference="annuel_jet10_base" typeTVA="S" />
<tarif id="1001" duree="12" engagement="12" frequence="5" prix="34.9" reference="annuel_jet10_base" typeTVA="S" />
<tarif id="1002" duree="12" engagement="12" frequence="6" prix="34.9" reference="annuel_jet10_base" typeTVA="S" />

</dataset>

=== oussama-denden/tos/opale-api/src/test/resources/dataset/get-commande-non-transforme-non-annule.xml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE dataset SYSTEM ".\src\test\resources\dtd\opale.dtd">
<dataset>
<commande/>
<commande id="1000" canal="welcome"  ip="GRC.WEL-JOHNDOE" ts="[now]" reference="REF-COMMANDE-1" referenceDraft="00000001" />
<commandeLigne/>
<commandeLigne id="1000" gamme="jet" modeFacturation="PREMIER_MOIS" referenceOffre="jet_surf10" commandeId="1000" secteur="sat" tarifId="1000"/>
<commandeLigneDetail/>
<tarif/>
<tarif id="1000" duree="12" engagement="12" frequence="12" prix="34.9" reference="annuel_jet10_base" typeTVA="S" />
<frais/>
</dataset>

=== oussama-denden/tos/src/test/resources/dataset/transforme-en-contrat.xml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE dataset SYSTEM "..\dtd\Opale.dtd">
<dataset>

<client id="1000" clientId="1000" adresseId="1000"/>
<client id="1001" clientId="1001" adresseId="1001"/>

<commande id="1000" canal="welcome" codePartenaire="part_123456" ip="GRC.WEL-JOHNDOE" qui="GRC.WEL-JOHNDOE" timestamp="[now]" reference="00000004" referenceDraft="00000004" clientAFacturerId="1000" clientALivrerId="1001"/>

<commandeLigne id="1000" qui="GRC.WEL-JOHNDOE" timestamp="[now]" gamme="jet" modeFacturation="PREMIER_MOIS" modePaiement="CB" referenceOffre="jet_surf10" commandeId="1000" famille="sat" tarifId="1006" />

<commandeLigneDetail id="1000" modePaiement="CB" referenceProduit="jet" label="Trafic 10 Gigas" typeProduit="SERVICE" dependDe="1001" commandeLigneId="1000" tarifId="1000" />
<commandeLigneDetail id="1001" modePaiement="CB" referenceProduit="kitsat" label="Trafic 10 Gigas" typeProduit="BIEN" commandeLigneId="1000" tarifId="1001" />


<tarif id="1000" duree="5" engagement="12" frequence="12" prix="34.9" reference="annuel_jet10_base" typeTVA="S" />
<tarif id="1001" duree="5" engagement="12" frequence="12" prix="34.9" reference="annuel_jet10_base" typeTVA="S" />
<tarif id="1002" duree="5" engagement="12" frequence="12" prix="34.9" reference="annuel_jet10_base" typeTVA="S" />
<tarif id="1004" duree="5" engagement="12" frequence="12" prix="34.9" reference="annuel_jet10_base" typeTVA="S" />
<tarif id="1005" duree="5" engagement="12" frequence="12" prix="34.9" reference="annuel_jet10_base" typeTVA="S" />
<tarif id="1006" duree="5" engagement="12" frequence="12" prix="34.9" reference="annuel_jet10_base" typeTVA="S" />

<frais id="1000" montant="50" typeTVA="S" typeFrais="RESILIATION" tarifId="1000" />
<frais id="1001" montant="50" typeTVA="S" typeFrais="RESILIATION" tarifId="1001" />
<frais id="1002" montant="50" typeTVA="S" typeFrais="RESILIATION" tarifId="1002" />
<frais id="1003" montant="50" typeTVA="S" typeFrais="CREATION" tarifId="1003" />
<frais id="1004" montant="50" typeTVA="S" typeFrais="RESILIATION" tarifId="1004" />
<frais id="1005" montant="50" typeTVA="S" typeFrais="CREATION" tarifId="1005" />
<frais id="1006" montant="50" typeTVA="S" typeFrais="RESILIATION" tarifId="1006" />
<frais id="1007" montant="50" typeTVA="S" typeFrais="RESILIATION" tarifId="1007" />

<paiement id="1000" montant="10" modePaiement="CB" reference="00000001" referenceCommande="00000004" canal="welcome" ip="127.0.0.1" qui="GRC.WEL-JOHNDOE" timestamp="[now]" />

</dataset>

=== oussama-denden/tos/opale-api/src/test/resources/dataset/calculer-cout-draft.xml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE dataset SYSTEM "..\dtd\Opale.dtd">

<dataset>
<client id="1000" adresseId="address-id" canal="welcome" clientId="client-id" timestamp="[now]" ip="1.1.1.1" qui="welcome" tva="00" />

<draft id="1000" canal="welcome" codePartenaire="PART_CODE" ip="127.0.0.1" qui="GRC.WEL-JOHNDOE" timestamp="[now]" reference="Dra-00000001"  />
<draft id="1001" canal="welcome" codePartenaire="PART_CODE" ip="127.0.0.1" qui="GRC.WEL-JOHNDOE" timestamp="[now]" reference="Dra-00000002"  />
<draft id="1002" canal="welcome" codePartenaire="PART_CODE" ip="127.0.0.1" qui="GRC.WEL-JOHNDOE" timestamp="[now]" reference="Dra-00000003" clientAFacturerId="1000" />

<draftLigne id="1000" canal="welcome" ip="127.0.0.1" qui="GRC.WEL-JOHNDOE" timestamp="[now]" reference="00000001" referenceOffre="jet_surf10" referenceTarif="annuel_jet10_base" draftId="1000" />
<draftLigne id="1001" canal="welcome" ip="127.0.0.1" qui="GRC.WEL-JOHNDOE" timestamp="[now]" reference="00000002" referenceOffre="jet_surf10" referenceTarif="annuel_jet10_base" draftId="1001" />
<draftLigne id="1002" canal="welcome" ip="127.0.0.1" qui="GRC.WEL-JOHNDOE" timestamp="[now]" reference="00000003" referenceOffre="jet_surf10" referenceTarif="annuel_jet10_base" draftId="1002" />

<draftLigneDetail id="1000" referenceChoix="kitsat" referenceSelection="kitsat" referenceTarif="mensuel_jet10_base" draftLigneId="1000" />
<draftLigneDetail id="1001" referenceChoix="jet" referenceSelection="jet" referenceTarif="mensuel_jet10_base" dependDe="1000" draftLigneId="1000" />
<draftLigneDetail id="1002" referenceChoix="trafic10g" referenceSelection="kitsat" referenceTarif="mensuel_jet10_base" draftLigneId="1001" />
<draftLigneDetail id="1003" referenceChoix="trafic10g" referenceSelection="kitTlf" referenceTarif="mensuel_jet10_base" dependDe="1002" draftLigneId="1001" />
<draftLigneDetail id="1004" referenceChoix="kitsat" referenceSelection="kitsat" referenceTarif="mensuel_jet10_base" draftLigneId="1002" />
<draftLigneDetail id="1005" referenceChoix="jet" referenceSelection="jet" referenceTarif="mensuel_jet10_base" dependDe="1004" draftLigneId="1002" />

<tarif id="1000" duree="5" engagement="12" frequence="5" prix="34.9" reference="annuel_jet10_base" typeTVA="S" />
<tarif id="1001" duree="12" engagement="12" frequence="5" prix="34.9" reference="annuel_jet10_base" typeTVA="S" />
<tarif id="1002" duree="12" engagement="12" frequence="6" prix="34.9" reference="annuel_jet10_base" typeTVA="S" />

</dataset>

=== oussama-denden/tos/opale-api/src/test/resources/dataset/get-list-paiement.xml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE dataset SYSTEM "..\dtd\Opale.dtd">

<dataset>
<commande id="1000" reference="REF-COMMANDE" />
<commandeLigne/>
<commandeLigneDetail/>
<tarif/>
<paiement id="1000" reference="REF-PAIEMENT-1" qui="auteur" montant="50" typePaiement="COMPTANT" modePaiement="CB" referenceCommande="REF-COMMANDE" />
<paiement id="1001" reference="REF-PAIEMENT-2" qui="auteur" montant="50" typePaiement="COMPTANT" modePaiement="CB" referenceCommande="REF-COMMANDE" />
<paiement id="1002" reference="REF-PAIEMENT-3" qui="auteur" montant="50" typePaiement="RECURRENT" modePaiement="SEPA" referenceCommande="REF-COMMANDE" />
<paiement id="1003" reference="REF-PAIEMENT-4" qui="auteur" montant="50" typePaiement="RECURRENT" modePaiement="SEPA" referenceCommande="REF-COMMANDE" />
</dataset>
