=== oussama-denden/tos/opale-api/src/test/resources/dtd/Opale.dtd
<!ELEMENT dataset (keygen*,client*,draft*, draftLigne*, draftLigneDetail*, commande*, commandeLigne*, commandeLigneDetail*, tarif*, frais*,signature*,paiement*,reduction*)>

<!ELEMENT draft EMPTY>
<!ATTLIST draft
    id CDATA #IMPLIED
    reference CDATA #IMPLIED
    clientAFacturerId CDATA #IMPLIED
    clientALivrerId CDATA #IMPLIED
    clientSouscripteurId CDATA #IMPLIED
    codePartenaire CDATA #IMPLIED
    qui CDATA #IMPLIED
    ip CDATA #IMPLIED
    canal CDATA #IMPLIED
    timestamp CDATA #IMPLIED
    referenceExterne CDATA #IMPLIED
    dateAnnulation  CDATA #IMPLIED
>
<!ELEMENT draftLigne EMPTY>
<!ATTLIST draftLigne
    id CDATA #IMPLIED
    reference CDATA #IMPLIED
    referenceTarif CDATA #IMPLIED
    dateCreation CDATA #IMPLIED
    qui CDATA #IMPLIED
    ip CDATA #IMPLIED
    canal CDATA #IMPLIED
    timestamp CDATA #IMPLIED
    draftId CDATA #IMPLIED
    referenceOffre CDATA #IMPLIED
     geste CDATA #IMPLIED
>
<!ELEMENT draftLigneDetail EMPTY>
<!ATTLIST draftLigneDetail
     id CDATA #IMPLIED
    referenceSelection CDATA #IMPLIED
    referenceChoix CDATA #IMPLIED
    referenceTarif CDATA #IMPLIED
    configurationJson CDATA #IMPLIED
    dependDe CDATA #IMPLIED
    draftLigneId CDATA #IMPLIED
>

<!ELEMENT tracage EMPTY>
<!ATTLIST tracage
     id CDATA #IMPLIED
    referenceDraft CDATA #IMPLIED
    action CDATA #IMPLIED
    user CDATA #IMPLIED
    date CDATA #IMPLIED
>

<!ELEMENT keygen EMPTY>
<!ATTLIST keygen
     id CDATA #IMPLIED
    referenceDraft CDATA #IMPLIED
    entite CDATA #IMPLIED
    prefix CDATA #IMPLIED
>

<!ELEMENT client EMPTY>
<!ATTLIST client
     id CDATA #IMPLIED
    adresseId CDATA #IMPLIED
    clientId CDATA #IMPLIED
    canal CDATA #IMPLIED
  ip  CDATA #IMPLIED
  qui  CDATA #IMPLIED
  timestamp  CDATA #IMPLIED
  tva CDATA #IMPLIED
>

<!ELEMENT commande EMPTY>
<!ATTLIST commande
    id CDATA #IMPLIED
    reference CDATA #IMPLIED
    referenceDraft CDATA #IMPLIED
    clientAFacturerId CDATA #IMPLIED
    clientALivrerId CDATA #IMPLIED
    clientSouscripteurId CDATA #IMPLIED
    dateCreation CDATA #IMPLIED
    dateTransformationContrat CDATA #IMPLIED
    dateAnnulation CDATA #IMPLIED
    qui CDATA #IMPLIED
    ip CDATA #IMPLIED
    canal CDATA #IMPLIED
    timestamp CDATA #IMPLIED
    codePartenaire CDATA #IMPLIED
   
>

<!ELEMENT commandeLigne EMPTY>
<!ATTLIST commandeLigne
    id CDATA #IMPLIED
    dateCreation CDATA #IMPLIED
    qui CDATA #IMPLIED
    ip CDATA #IMPLIED
    canal CDATA #IMPLIED
    timestamp CDATA #IMPLIED
    gamme CDATA #IMPLIED
    label CDATA #IMPLIED
    modeFacturation CDATA #IMPLIED
    typeProduit CDATA #IMPLIED
    referenceOffre CDATA #IMPLIED
    referenceContrat CDATA #IMPLIED
    secteur CDATA #IMPLIED
    commandeId CDATA #IMPLIED
    tarifId CDATA #IMPLIED
    geste CDATA #IMPLIED
>

<!ELEMENT commandeLigneDetail EMPTY>
<!ATTLIST commandeLigneDetail
    id CDATA #IMPLIED
    configurationJson CDATA #IMPLIED
    referenceSelection CDATA #IMPLIED
    referenceChoix CDATA #IMPLIED
    label CDATA #IMPLIED
    typeProduit CDATA #IMPLIED
    dependDe CDATA #IMPLIED
    commandeLigneId CDATA #IMPLIED
    tarifId CDATA #IMPLIED
>

<!ELEMENT tarif EMPTY>
<!ATTLIST tarif
     id CDATA #IMPLIED
    duree CDATA #IMPLIED
    engagement CDATA #IMPLIED
    frequence CDATA #IMPLIED
    prix CDATA #IMPLIED
    reference CDATA #IMPLIED
    typeTVA CDATA #IMPLIED
>

<!ELEMENT frais EMPTY>
<!ATTLIST frais
     id CDATA #IMPLIED
    label CDATA #IMPLIED
    montant CDATA #IMPLIED
    politique CDATA #IMPLIED
    politiqueIndex CDATA #IMPLIED
    reference CDATA #IMPLIED
    typeFrais CDATA #IMPLIED
    tarifId CDATA #IMPLIED
>

<!ELEMENT signature EMPTY>
<!ATTLIST signature
    id CDATA #IMPLIED
    reference CDATA #IMPLIED
    mode CDATA #IMPLIED
    timestampSignature CDATA #IMPLIED
    footprint CDATA #IMPLIED
    idSignature  CDATA #IMPLIED
    qui CDATA #IMPLIED
    ip CDATA #IMPLIED
    canal CDATA #IMPLIED
    timestamp CDATA #IMPLIED
    referenceCommande CDATA #IMPLIED
    dateAnnulation  CDATA #IMPLIED
    timestampIntention CDATA #IMPLIED
    dateCreation CDATA #IMPLIED
>

<!ELEMENT paiement EMPTY>
<!ATTLIST paiement
    id CDATA #IMPLIED
    infoPaiement CDATA #IMPLIED
    modePaiement CDATA #IMPLIED
    montant CDATA #IMPLIED
    reference CDATA #IMPLIED
    referenceCommande CDATA #IMPLIED
    qui CDATA #IMPLIED
    ip CDATA #IMPLIED
    canal CDATA #IMPLIED
    timestamp CDATA #IMPLIED
    timestampIntention CDATA #IMPLIED
    timestampPaiement CDATA #IMPLIED
    typePaiement CDATA #IMPLIED
    dateCreation CDATA #IMPLIED
>

<!ELEMENT reduction EMPTY>
<!ATTLIST reduction
    id CDATA #IMPLIED
    dateDebut CDATA #IMPLIED
    dateFin CDATA #IMPLIED
    label CDATA #IMPLIED
    nbUtilisationMax CDATA #IMPLIED
    reference CDATA #IMPLIED
    referenceDraft CDATA #IMPLIED
    referenceFrais CDATA #IMPLIED
    referenceLigne CDATA #IMPLIED
    referenceLigneDetail CDATA #IMPLIED
    referenceTarif CDATA #IMPLIED
    typeValeur CDATA #IMPLIED
    valeur CDATA #IMPLIED
    referenceReduction CDATA #IMPLIED
>

=== oussama-denden/tos/src/test/resources/dataset/transformer-en-draft.xml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE dataset SYSTEM "..\dtd\Opale.dtd">
<dataset>
<client id="1000" adresseId="adr-fac" clientId="cl-fac"  qui="someone" timestamp="[now]"/>
<client id="1001" adresseId="adr-sousc" clientId="cl-sousc"   qui="someone" timestamp="[now]"/>
<client id="1002" adresseId="adr-liv" clientId="cl-livc"   qui="someone" timestamp="[now]"/>

<commande id="1000" canal="welcome" codePartenaire="part_123456" ip="GRC.WEL-JOHNDOE" timestamp="[now]" reference="00000001" referenceDraft="00000001" clientAFacturerId="1000" clientSouscripteurId="1001" clientALivrerId="1002" />

<commandeLigne id="1000" canal="welcome"  ip="GRC.WEL-JOHNDOE" timestamp="[now]" gamme="jet" modeFacturation="PREMIER_MOIS" referenceOffre="jet_surf10" commandeId="1000" famille="sat" tarifId="1002" />

<commandeLigneDetail id="1000" referenceChoix="jet" label="Trafic 10 Gigas" typeProduit="SERVICE" dependDe="1001" commandeLigneId="1000" tarifId="1000" />
<commandeLigneDetail id="1001" referenceChoix="kitsat" label="Trafic 10 Gigas" typeProduit="BIEN" commandeLigneId="1000" tarifId="1001" />

<tarif id="1000" duree="5" engagement="12" frequence="5" prix="34.9" reference="annuel_jet10_base" typeTVA="S" />
<tarif id="1001" duree="12" engagement="12" frequence="5" prix="34.9" reference="annuel_jet10_base" typeTVA="S" />
<tarif id="1002" duree="12" engagement="12" frequence="6" prix="34.9" reference="annuel_jet10_base" typeTVA="S" />

<frais id="1000" montant="50" typeTVA="S" typeFrais="CREATION" tarifId="1000" />
<frais id="1001" montant="50" typeTVA="S" typeFrais="RESILIATION" tarifId="1001" />
<frais id="1002" montant="50" typeTVA="S" typeFrais="RESILIATION" tarifId="1002" />

</dataset>

=== oussama-denden/tos/src/test/resources/dataset/is-besoin-paiement-recurrent.xml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE dataset SYSTEM "..\dtd\Opale.dtd">
<dataset>
<commande id="1000" canal="welcome" code="part_123456" ip="GRC.WEL-JOHNDOE" timestamp="1411654933" reference="00000001" referenceDraft="00000001" />
<commande id="1001" canal="welcome" code="part_123456" ip="GRC.WEL-JOHNDOE" timestamp="1411654933" reference="00000002" referenceDraft="00000002" />
<commande id="1002" canal="welcome" code="part_123456" ip="GRC.WEL-JOHNDOE" timestamp="1411654933" reference="00000003" referenceDraft="00000003" />

<commandeLigne id="1000" gamme="jet" modeFacturation="PREMIER_MOIS" modePaiement="CB" referenceOffre="jet_surf10" commandeId="1000" famille="sat" tarifId="1002" />
<commandeLigne id="1001" gamme="jet" modeFacturation="PREMIER_MOIS" modePaiement="CB" referenceOffre="jet_surf10" commandeId="1001" famille="sat" tarifId="1006" />
<commandeLigne id="1002" gamme="jet" modeFacturation="PREMIER_MOIS" modePaiement="CB" referenceOffre="jet_surf10" commandeId="1002" famille="sat" tarifId="1007" />

<commandeLigneDetail id="1000" modePaiement="CB" referenceProduit="jet" label="Trafic 10 Gigas" typeProduit="SERVICE" dependDe="1001" commandeLigneId="1000" tarifId="1000" />
<commandeLigneDetail id="1001" modePaiement="CB" referenceProduit="kitsat" label="Trafic 10 Gigas" typeProduit="BIEN" commandeLigneId="1000" tarifId="1001" />
<commandeLigneDetail id="1002" modePaiement="CB" referenceProduit="jet" label="Trafic 10 Gigas" typeProduit="SERVICE" dependDe="1003" commandeLigneId="1001" tarifId="1004" />
<commandeLigneDetail id="1003" modePaiement="CB" referenceProduit="kitsat" label="Trafic 10 Gigas" typeProduit="BIEN" commandeLigneId="1001" tarifId="1005" />
<commandeLigneDetail id="1004" modePaiement="CB" referenceProduit="jet" label="Trafic 10 Gigas" typeProduit="SERVICE" dependDe="1003" commandeLigneId="1002" tarifId="1008" />
<commandeLigneDetail id="1005" modePaiement="CB" referenceProduit="kitsat" label="Trafic 10 Gigas" typeProduit="BIEN" commandeLigneId="1002" tarifId="1009" />

<tarif id="1000" duree="5" engagement="12" frequence="5" prix="34.9" reference="annuel_jet10_base" typeTVA="S" />
<tarif id="1001" duree="12" engagement="12" frequence="12" prix="34.9" reference="annuel_jet10_base" typeTVA="S" />
<tarif id="1002" duree="12" engagement="12" frequence="12" prix="34.9" reference="annuel_jet10_base" typeTVA="S" />
<tarif id="1004" duree="5" engagement="12" frequence="5" prix="34.9" reference="annuel_jet10_base" typeTVA="S" />
<tarif id="1005" duree="12" engagement="12" frequence="6" prix="34.9" reference="annuel_jet10_base" typeTVA="S" />
<tarif id="1006" duree="12" engagement="12" frequence="5" prix="34.9" reference="annuel_jet10_base" typeTVA="S" />
<tarif id="1007" duree="5" engagement="12" frequence="5" prix="34.9" reference="annuel_jet10_base" typeTVA="S" />
<tarif id="1008" duree="12" engagement="12" frequence="6" prix="34.9" reference="annuel_jet10_base" typeTVA="S" />
<tarif id="1009" duree="12" engagement="12" frequence="5" prix="34.9" reference="annuel_jet10_base" typeTVA="S" />

<frais id="1000" montant="50" typeTVA="S" typeFrais="CREATION" tarifId="1000" />
<frais id="1001" montant="50" typeTVA="S" typeFrais="RESILIATION" tarifId="1001" />
<frais id="1002" montant="50" typeTVA="S" typeFrais="RESILIATION" tarifId="1002" />
<frais id="1004" montant="50" typeTVA="S" typeFrais="RESILIATION" tarifId="1004" />
<frais id="1005" montant="50" typeTVA="S" typeFrais="CREATION" tarifId="1005" />
<frais id="1006" montant="50" typeTVA="S" typeFrais="RESILIATION" tarifId="1006" />
<frais id="1007" montant="50" typeTVA="S" typeFrais="RESILIATION" tarifId="1007" />
<frais id="1008" montant="50" typeTVA="S" typeFrais="CREATION" tarifId="1008" />
<frais id="1009" montant="50" typeTVA="S" typeFrais="RESILIATION" tarifId="1009" />

<paiement id="1000" montant="90" modePaiement="CB" reference="00000001" referenceCommande="00000001" typePaiement="COMPTANT" canal="welcome" ip="127.0.0.1" qui="GRC.WEL-JOHNDOE" timestamp="123456879" timestampIntention="[now]" timestampPaiement="[now]" code="part_123456" />
<paiement id="1001" montant="90" modePaiement="CB" reference="00000001" referenceCommande="00000003" typePaiement="RECURRENT" canal="welcome" ip="127.0.0.1" qui="GRC.WEL-JOHNDOE" timestamp="123456879" timestampPaiement="[now]" code="part_123456" />
</dataset>

=== oussama-denden/tos/src/test/resources/dataset/transformer-en-commande.xml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE dataset SYSTEM "..\dtd\Opale.dtd">

<dataset>
	<keygen />
	<draft />
	<draft id="1" reference="REF-DRAFT-1" code="000111"
		timestamp="100" />
	<draft id="2" reference="REF-DRAFT-3" code="000111"
		timestamp="100" />

	<draft id="3" reference="REF-DRAFT-4" code="000111"
		timestamp="100" />
	<draftLigne />
	<draftLigne id="1000" reference="00000001" referenceTarif="mensuel_jet10_base"
		referenceOffre="jet_surf10" modePaiement="CB" modeFacturation="DATE_ANNIVERSAIRE"
		code="part_123456" qui="GRC.WEL-JOHNDOE" canal="Welcome" ip="127.0.0.1"
		timestamp="1411654933" draftId="1" />

	<draftLigne id="1001" reference="00000002" referenceTarif="mensuel_jet10_base"
		referenceOffre="jet_surf100" modePaiement="CB" modeFacturation="DATE_ANNIVERSAIRE"
		code="part_123456" qui="GRC.WEL-JOHNDOE" canal="Welcome" ip="127.0.0.1"
		timestamp="1411654933" draftId="2" />

	<draftLigne id="1002" reference="00000003" referenceTarif="mensuel_jet10_base"
		referenceOffre="jet_surf10" modePaiement="CB" modeFacturation="DATE_ANNIVERSAIRE"
		code="part_123456" qui="GRC.WEL-JOHNDOE" canal="Welcome" ip="127.0.0.1"
		timestamp="1411654933" draftId="3" />

	<draftLigneDetail />
	<draftLigneDetail id="1000" referenceSelection="kitsat" referenceChoix="trafic10g"
		reference="kitsat" referenceTarif="mensuel_jet10_base" modePaiement="CB"
		configurationJson="" draftLigneId="1000" />
	<draftLigneDetail id="1001" referenceSelection="jet" referenceChoix="trafic10g"
		reference="jet" referenceTarif="mensuel_jet10_base" modePaiement="CB"
		configurationJson="" draftLigneId="1000" dependDe="1000" />

	<draftLigneDetail id="1002" referenceSelection="kitsat" referenceChoix="trafic10g"
		reference="kitsat" referenceTarif="mensuel_jet10_base" modePaiement="CB"
		configurationJson="" draftLigneId="1001" />
	<draftLigneDetail id="1003" referenceSelection="jet" referenceChoix="trafic10g"
		reference="jet" referenceTarif="mensuel_jet10_base" modePaiement="CB"
		configurationJson="" draftLigneId="1001" dependDe="1000" />

	<draftLigneDetail id="1004" referenceSelection="kitsat10" referenceChoix="trafic10g"
		reference="kitsat10" referenceTarif="mensuel_jet10_base" modePaiement="CB"
		configurationJson="" draftLigneId="1002" />

</dataset>

=== oussama-denden/tos/opale-api/src/test/resources/dataset/calculer-cout-commande.xml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE dataset SYSTEM "..\dtd\Opale.dtd">

<dataset>
<client id="1000" adresseId="address-facturation" clientId="client-id" ip="1.1.1.1" ts="[now]" qui="TEST" tva="00" />

<commande id="1000" canal="welcome"  ip="GRC.WEL-JOHNDOE" ts="[now]" reference="Cmd-00000001" referenceDraft="00000001" clientAFacturerId="1000" />

<commandeLigne id="1000" gamme="jet" modeFacturation="PREMIER_MOIS" referenceOffre="jet_surf10" commandeId="1000" secteur="sat" tarifId="1002" />

<commandeLigneDetail id="1000" referenceChoix="jet" label="Trafic 10 Gigas" typeProduit="SERVICE" dependDe="1001" commandeLigneId="1000" tarifId="1000" />
<commandeLigneDetail id="1001" referenceChoix="kitsat" label="Trafic 10 Gigas" typeProduit="BIEN" commandeLigneId="1000" tarifId="1001" />

<tarif id="1000" duree="1" engagement="12" frequence="1" prix="34.9" reference="annuel_jet10_base" typeTVA="S" />
<tarif id="1001" duree="1" engagement="12" frequence="1" prix="34.9" reference="annuel_jet10_base" typeTVA="S" />
<tarif id="1002" duree="12" engagement="12" frequence="1" prix="34.9" reference="annuel_jet10_base" typeTVA="S" />

<frais id="1000" montant="50" typeFrais="CREATION" tarifId="1002" />
<frais id="1001" montant="50" typeFrais="RESILIATION" tarifId="1001" />
<frais id="1002" montant="50" typeFrais="RESILIATION" tarifId="1000" />

</dataset>
